spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USER}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update

spring.jpa.properties.hibernate.jdbc.batch_size=1000
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true

server.port=8080

mimit.carburanti.stations-url=https://www.mimit.gov.it/images/exportCSV/anagrafica_impianti_attivi.csv
mimit.carburanti.prices-url=https://www.mimit.gov.it/images/exportCSV/prezzo_alle_8.csv

# Locale
#mimit.carburanti.stations-url=file:/Users/11624973/Downloads/carburanti/anagrafica_impianti_attivi.csv
#mimit.carburanti.prices-url=file:/Users/11624973/Downloads/carburanti/prezzo_alle_8.csv